<?php
class Cylinder extends Circle{
    public float $heigth;
    public function __construct($radius, $color,$heigth)
    {
        parent::__construct($radius, $color);
        $this->heigth=$heigth;
    }
    public function calculatorArea(): float|int
    {
        return parent::calculatorArea() *2 + parent::calculatorPerimeter()*$this->heigth; // TODO: Change the autogenerated stub
    }
    public function calculatorVolume():float|int
    {
        return parent::calculatorArea() *$this->heigth;
    }
    public function toString()
    {
        parent::toString();
        echo ",height=".$this->heigth;// TODO: Change the autogenerated stub
    }
}
